GET http://localhost:3000/

################################
POST http://localhost:3000/user/register/
Content-Type: application/json

{
    "email": "thien@gmail.com",
    "password": "abc123456"
}
################################
POST http://localhost:3000/user/refresh-token/
Content-Type:  application/json

{
    "refreshToken":"seyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWE4YTRjNWE4YTI5YmQ0ZTE3ZGNjNzgiLCJpYXQiOjE2Mzg1MzQyMjQsImV4cCI6MTY3MDA5MTgyNH0.Y_kHWDXaJR6Me6M3bB6aSiche3F8-TBRJfkHTg2PN1c"
}
###############################
POST http://localhost:3000/user/login/
Content-Type: application/json

{
    "email": "thien@gmail.com",
    "password": "abc123456"
}

###############################
DELETE http://localhost:3000/user/logout/
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWE4YTRjNWE4YTI5YmQ0ZTE3ZGNjNzgiLCJpYXQiOjE2Mzg1MzQyMzEsImV4cCI6MTY3MDA5MTgzMX0.rhqjalXDGS0yf8BzpOIk5Nf98DtZTAtS9SyhxvCu31E"
}
###############################
GET http://localhost:3000/user/getlist/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWE4YTRjNWE4YTI5YmQ0ZTE3ZGNjNzgiLCJpYXQiOjE2Mzg1MDc5NjMsImV4cCI6MTYzODUxMTU2M30.2FQPFdpj8w4u96eW7ZIYUCh8cwKY9st9Radw3wcgHcY