GET http://localhost:3000/

################################
POST http://localhost:3000/user/register/
Content-Type: application/json

{
    "name": "Thien",
    "address": "78 Bà Hom, phường 13, quận 6",
    "birthdate": "03/12/1999",
    "email": "thien@gmail.com",
    "password": "abc123456"
}
################################
POST http://localhost:3000/user/refresh-token/
Content-Type:  application/json

{
    "refreshToken":"seyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWE4YTRjNWE4YTI5YmQ0ZTE3ZGNjNzgiLCJpYXQiOjE2Mzg1MzQyMjQsImV4cCI6MTY3MDA5MTgyNH0.Y_kHWDXaJR6Me6M3bB6aSiche3F8-TBRJfkHTg2PN1c"
}
###############################
POST http://localhost:3000/user/login/
Content-Type: application/json

{

    "email": "thien@gmail.com",
    "password": "abc123456"
}

###############################
DELETE http://localhost:3000/user/logout/
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWFmNzUxNzEzMGE4N2M1NTNiMzMzNmIiLCJpYXQiOjE2Mzg4ODk1NjIsImV4cCI6MTYzODg4OTg2Mn0.uW8jOEVVuDWgLhXQ4iem1Ik1tkxGnInCsoUiuIl9NaM"
}
###############################
GET http://localhost:3000/user/getlist/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWFmNzUxNzEzMGE4N2M1NTNiMzMzNmIiLCJpYXQiOjE2Mzg4OTA0MjUsImV4cCI6MTYzODg5MDcyNX0.V3Zx4mv3j4ITz_w2LINUZmt_9gRm9TOu_aQTQQSZOdQ
################################
GET http://localhost:3000/user/getinfo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWFmNzUxNzEzMGE4N2M1NTNiMzMzNmIiLCJpYXQiOjE2Mzg4OTA3NTYsImV4cCI6MTYzODg5NDM1Nn0.kJhh4dM9ys6C6ZzR9z2P5hSOmkDmeOpZSI9SjM0GwLE